---
title: "Data424 Final"
author: "Connor"
date: "11/27/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clears global environment 
```{r, include=FALSE}
rm(list = ls(all.names = TRUE))
```

```{r}
#packages
library(tidyr)
library(dplyr)
library(leaps)
library(psych)
library(ggplot2)
```

```{r}
ames = read.csv("House.csv")
```

```{r}
ames = ames %>% tidyr::replace_na(list(BsmtQual = "none", BsmtCond = "none", BsmtExposure="none", 
                                       BsmtFinType1="none",BsmtFinType2="none", FireplaceQu="none", 
                                       GarageQual="none", GarageCond="none", PoolQC="none",Fence="none",
                                       MiscFeature="none", Alley="none", GarageType="none",GarageFinish="none",
                                       GarageYrBlt=round(mean(ames$GarageYrBlt, na.rm=TRUE))))
```

```{r}
ames2 = ames %>% drop_na()
```

```{r}
ames2 = as.data.frame(unclass(ames2), stringsAsFactors = TRUE)
factors = sapply(ames2, is.factor)
str(ames2)
```

```{r}
lmames = lm(SalePrice~MSSubClass++LotFrontage+LotArea+as.numeric(Neighborhood)+
              OverallQual+YearBuilt+as.numeric(RoofMatl)+
              MasVnrArea+as.numeric(ExterQual)+as.numeric(BsmtQual)+
              as.numeric(BsmtExposure)+TotalBsmtSF+GrLivArea+BsmtFullBath+
              BedroomAbvGr+as.numeric(KitchenQual)+as.numeric(Functional)+
              Fireplaces+GarageCars+ScreenPorch+
              as.numeric(SaleCondition), data=ames2)
summary(lmames)
```

```{r}
aic_ames = step(lmames, k=2)
aic_ames_log = step(lmames, k=log(1194))
anova(aic_ames_log)
```

```{r}
lmames2 = lmames = lm(SalePrice~MSSubClass++LotFrontage+LotArea+as.numeric(Neighborhood)+
              OverallQual+YearBuilt+as.numeric(RoofMatl)+
              MasVnrArea+as.numeric(ExterQual)+as.numeric(BsmtQual)+
              as.numeric(BsmtExposure)+GrLivArea+
              BedroomAbvGr+as.numeric(KitchenQual)+as.numeric(Functional)+
              Fireplaces+GarageCars+ScreenPorch+
              as.numeric(SaleCondition), data=ames2)
summary(lmames2)
```

```{r}
aic_ames2 = step(lmames2, k=2)
aic_ames_log2 = step(lmames2, k=log(1194))
anova(aic_ames2)
anova(aic_ames_log2)
```

```{r}
b = regsubsets(SalePrice~MSSubClass++LotFrontage+LotArea+as.numeric(Neighborhood)+
              OverallQual+YearBuilt+as.numeric(RoofMatl)+
              MasVnrArea+as.numeric(ExterQual)+as.numeric(BsmtQual)+
              as.numeric(BsmtExposure)+GrLivArea+
              BedroomAbvGr+as.numeric(KitchenQual)+as.numeric(Functional)+
              Fireplaces+GarageCars+ScreenPorch+
              as.numeric(SaleCondition), data=ames2)
summary(b)
summary(b)$adjr2
```

```{r}
lmames3 = lm(SalePrice~as.numeric(BsmtQual)+as.numeric(BsmtExposure)+
              as.numeric(KitchenQual)+GarageCars+GrLivArea+MSSubClass+
              OverallQual+OverallQual+YearBuilt+MasVnrArea, data=ames2)
summary(lmames3)
```

```{r}
b2 = regsubsets(SalePrice~as.numeric(BsmtQual)+as.numeric(BsmtExposure)+
              as.numeric(KitchenQual)+GarageCars+GrLivArea+MSSubClass+
              OverallQual+OverallQual+YearBuilt+MasVnrArea, data=ames2)
summary(b2)
summary(b2)$cp
summary(b2)$adjr2
```

```{r}
aic_ames3 = step(lmames3, k=2)
aic_ames_log3 = step(lmames3, k=log(1194))
anova(aic_ames3)
anova(aic_ames_log3)
```

```{r}
#cor(lmames3)
```

Plots
```{r}
plot(lmames3)
```

```{r}
ames2$residuals = lmames3$residuals
ames2$predicted = predict(lmames3)
plot(ames2$predicted, ames2$residuals)
```

